### ISSUE TITLE
Änderungswünsche laut Auftraggeber vom 7.9.2022

### ISSUE THREAD

**Issue by ahocevar** [w3geo/agraratlas#44]
- [x]  #48 Ab Zoomstufe 12 automatisch immer nur die im Kartenausschnitt sichtbaren Themen zeigen, der Schalter "Nur Themen im Kartenausschnitt" soll weg. Wenn ein Schlag gewählt ist, kann man die im Kartenausschnitt sichtbaren Themen zusätzlich mit dem "Nur für den Schlag mögliche Themen" weiter einschränken
- [x]  #47 Die Auswahlmöglichkeiten "Nur Hintergrundkarte" und "Übersicht über alle Themen" sollen weg. Es gibt dann keine Kartenansicht mehr, wo man mehrere bzw. alle Themen sieht.
- [x]  #46 Um den gewählten Schlag wieder abwählen zu können, soll zusätzlich zum Klick außerhalb der Schläge auch ein erneuter Klick in den gewählten Schlag zur Deselektion führen.
